//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ruscehproj2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ruscehproj2.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap bg001 {
            get {
                object obj = ResourceManager.GetObject("bg001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg002 {
            get {
                object obj = ResourceManager.GetObject("bg002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg003 {
            get {
                object obj = ResourceManager.GetObject("bg003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg004 {
            get {
                object obj = ResourceManager.GetObject("bg004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg005 {
            get {
                object obj = ResourceManager.GetObject("bg005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BigSwOff {
            get {
                object obj = ResourceManager.GetObject("BigSwOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BigSwOn {
            get {
                object obj = ResourceManager.GetObject("BigSwOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bm005 {
            get {
                object obj = ResourceManager.GetObject("bm005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bp103 {
            get {
                object obj = ResourceManager.GetObject("bp103", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bp116 {
            get {
                object obj = ResourceManager.GetObject("bp116", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bp119 {
            get {
                object obj = ResourceManager.GetObject("bp119", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap br003 {
            get {
                object obj = ResourceManager.GetObject("br003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap br004 {
            get {
                object obj = ResourceManager.GetObject("br004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap br007 {
            get {
                object obj = ResourceManager.GetObject("br007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BSH001 {
            get {
                object obj = ResourceManager.GetObject("BSH001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BSH002 {
            get {
                object obj = ResourceManager.GetObject("BSH002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BSH003 {
            get {
                object obj = ResourceManager.GetObject("BSH003", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bv004 {
            get {
                object obj = ResourceManager.GetObject("bv004", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bv010 {
            get {
                object obj = ResourceManager.GetObject("bv010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bv012 {
            get {
                object obj = ResourceManager.GetObject("bv012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bya001 {
            get {
                object obj = ResourceManager.GetObject("bya001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap display {
            get {
                object obj = ResourceManager.GetObject("display", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grLight {
            get {
                object obj = ResourceManager.GetObject("grLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1251&quot;?&gt;
        ///&lt;helpdb&gt;
        ///	&lt;hlpEntry&gt;
        ///		&lt;id&gt;1&lt;/id&gt;
        ///		&lt;hlpString&gt;Данный сценарий разбирает включение и проверку системы в режиме Местный Ремонт. Откройте пожалуйста блок ЩП-001!&lt;/hlpString&gt;
        ///		&lt;blockId&gt;none&lt;/blockId&gt;
        ///		&lt;posx&gt;100&lt;/posx&gt;
        ///		&lt;posy&gt;200&lt;/posy&gt;
        ///	&lt;/hlpEntry&gt;
        ///	&lt;hlpEntry&gt;
        ///		&lt;id&gt;2&lt;/id&gt;
        ///		&lt;hlpString&gt;Переведите тумблер РЕЖИМ. РАБ. в положение МЕСТН.РЕМ.&lt;/hlpString&gt;
        ///		&lt;blockId&gt;shp001&lt;/blockId&gt;
        ///		&lt;posx&gt;&lt;/posx&gt;
        ///		&lt;posy&gt;&lt;/posy&gt;
        ///	&lt;/hlpEntry&gt;
        ///	&lt;hlpEntry&gt;
        ///		&lt;id&gt;3&lt;/id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helpdb {
            get {
                return ResourceManager.GetString("helpdb", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap null256 {
            get {
                object obj = ResourceManager.GetObject("null256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap oldSwitchRed {
            get {
                object obj = ResourceManager.GetObject("oldSwitchRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap oldSwitchWhite {
            get {
                object obj = ResourceManager.GetObject("oldSwitchWhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap S4010063 {
            get {
                object obj = ResourceManager.GetObject("S4010063", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set0 {
            get {
                object obj = ResourceManager.GetObject("set0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set01 {
            get {
                object obj = ResourceManager.GetObject("set01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set02 {
            get {
                object obj = ResourceManager.GetObject("set02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set03 {
            get {
                object obj = ResourceManager.GetObject("set03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set04 {
            get {
                object obj = ResourceManager.GetObject("set04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set1 {
            get {
                object obj = ResourceManager.GetObject("set1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set10 {
            get {
                object obj = ResourceManager.GetObject("set10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set11 {
            get {
                object obj = ResourceManager.GetObject("set11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set12 {
            get {
                object obj = ResourceManager.GetObject("set12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set13 {
            get {
                object obj = ResourceManager.GetObject("set13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set14 {
            get {
                object obj = ResourceManager.GetObject("set14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set15 {
            get {
                object obj = ResourceManager.GetObject("set15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set2 {
            get {
                object obj = ResourceManager.GetObject("set2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set3 {
            get {
                object obj = ResourceManager.GetObject("set3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set4 {
            get {
                object obj = ResourceManager.GetObject("set4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set5 {
            get {
                object obj = ResourceManager.GetObject("set5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set6 {
            get {
                object obj = ResourceManager.GetObject("set6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set7 {
            get {
                object obj = ResourceManager.GetObject("set7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set8 {
            get {
                object obj = ResourceManager.GetObject("set8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set9 {
            get {
                object obj = ResourceManager.GetObject("set9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shp001 {
            get {
                object obj = ResourceManager.GetObject("shp001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sw1 {
            get {
                object obj = ResourceManager.GetObject("sw1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sw2 {
            get {
                object obj = ResourceManager.GetObject("sw2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
